# Generated by Django 3.0.6 on 2020-05-08 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_number',
            new_name='x',
        ),
    ]
